-- Execute apenas se a tabela pre_autorizados ainda não tiver estas colunas.
create table if not exists public.pre_autorizados (
  id bigint generated by default as identity primary key,
  nome text not null,
  nome_normalizado text not null,
  empresa text,
  regional text,
  area text,
  arquivo_origem text,
  atualizado_em timestamptz not null default now()
);
create index if not exists pre_autorizados_nome_normalizado_idx on public.pre_autorizados(nome_normalizado);
